#Provide the taskId if you are updating the task
task_id: '4UYDF7JjsHwxTQWS5yNTDLyywgjhFNoyKcTwtkbcDRVR'
# Name and desciption of your task
task_name: 'Twitter Crawler v3'
task_description: 'Crawls for all tweets with #koii and stores them on IPFS.'

# network value can be DEVELOPMENT , ARWEAVE or IPFS
task_executable_network: 'IPFS'

# Provide your web3.storage key as it is needed for uploading your metadata
secret_web3_storage_key: ''

# last deploy : date: 2021-05-10T12:00:00.000Z
# Task Id: 4UYDF7JjsHwxTQWS5yNTDLyywgjhFNoyKcTwtkbcDRVR
# Stake Pot Account Pubkey: stakepotaccountoAu3FaRrZwh2daX2s6wLDZyQaTRk

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: 'dist/main.js'

# Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: ''

# Total round time of your task : it must be given in slots and each slot is roughly equal to 4ms
round_time: 6000

audit_window: 2000
submission_window: 2000

# Amounts in KOII

minimum_stake_amount: 5

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 1000

bounty_amount_per_round: 100

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 4

#Space in MBs
space: 5

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

author: 'author'
description: 'This task volunteers your spare Twitter account to help us archive the #koii hashtag community. This is a not-for-profit endeavor, sponsored by the Koii Foundation :)'
repositoryUrl: 'https://github.com/GET-store-CAT/twitter-crawler'
imageUrl: 'https://ichef.bbci.co.uk/news/976/cpsprodpb/16620/production/_91408619_55df76d5-2245-41c1-8031-07a4da3f313f.jpg'
requirementsTags:
  - type: TASK_VARIABLE
    value: 'WEB3STORAGE_TOKEN'
    description: 'Used to upload data to IPFS - get 1GB for free at https://web3.storage/'
  - type: TASK_VARIABLE
    value: 'TWITTER_USERNAME'
    description: 'The username of your volunteer Twitter account.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PASSWORD'
    description: 'The password of your volunteer Twitter account.'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: 'Some'
  - type: NETWORK
    value: 'Fast'
  - type: ARCHITECTURE
    value: 'AMD'
  - type: OS
    value: 'OSX'